config/routes.rb
HidUi::Engine.routes.draw do
  post 'identify', to: 'Application#identify'
  post 'map', to: 'Application#map'
  post 'delete', to: 'Application#delete'
  post 'clear', to: 'Application#clear'
  root to: 'Application#index'
end

app/models/hid_ui/identity.rb
module HidUi
  class Identity < ActiveRecord::Base
    attr_accessible :input, :identity, :id_type

    class Identifier
      @identity_class = Identity
      @recorder_class = Record::Recorder
      class << self
        attr_accessor :identity_class, :recorder_class

        def find(input, type)
          identity = identity_class.where(input: input, id_type: type).first
          identity && identity.identity
        end

        def map(input, identity, type)
          unless identity_class.where(input: input, identity: identity, id_type: type).exists?
            identity_class.create input: input, identity: identity, id_type: type
          end
          recorder_class.remove(input, type)
          nil
        end
      end
    end
  end
end

app/models/hid_ui/record.rb
module HidUi
  class Record < ActiveRecord::Base
    attr_accessible :input, :id_type

    class Recorder
      @record_class = Record
      class << self
        attr_accessor :record_class

        def record(input, type)
          unless record_class.where(input: input, id_type: type).exists?
            record_class.create input: input, id_type: type
          end
          nil
        end

        def remove(input, type)
          record_class.where(input: input, id_type: type).destroy_all
        end

        def recorded(type)
          return typed_records(type) if type
          untyped_records
        end

        private

        def typed_records(type)
          record_class.where(id_type: type).pluck(:input)
        end

        def untyped_records
          record_groups = record_class.all.group_by(&:id_type)
          hash = Hash.new

          record_groups.each do |type, records|
            hash[type] = records.map(&:input) if records
          end

          hash
        end
      end
    end
  end
end

app/controllers/hid_ui/application_controller.rb
module HidUi
  class ApplicationController < ActionController::Base
    def index
      @identities = HidUi::Identity.where id_type: 'Example::Type'
      @misses     = HidCore.recorded 'Example::Type'
    end

    def identify
      if input
        identified_input= HidCore.identify input, 'Example::Type'
        if identified_input
          flash[:identify] = "Identified \"#{input}\" as \"#{identified_input}\"."
        else
          flash[:identify] = "Could not identify \"#{input}\"."
        end
      else
        flash[:identify] = "Please input something."
      end
      redirect_to root_path
    end

    def map
      if input && identity
        HidCore.map input, identity, 'Example::Type'
        flash[:map] = "Mapped \"#{input}\" to \"#{identity}\"."
      else
        flash[:clear] = "Please enter an identity."
      end
      redirect_to root_path
    end

    def delete
      HidUi::Identity.where(input: input, identity: identity, id_type: 'Example::Type').destroy_all
      flash[:delete] = "Deleted mapping \"#{input}\" to \"#{identity}\"."
      redirect_to root_path
    end

    def clear
      HidUi::Record.destroy_all
      flash[:clear] = 'Cleared all recorded misses.'
      redirect_to root_path
    end

    private

    def identity
      params[:identity].presence
    end

    def input
      params[:input].presence
    end
  end
end

app/helpers/hid_ui/application_helper.rb
module HidUi
  module ApplicationHelper
  end
end

app/views/hid_ui/application/index.html.erb
<div class='container'>
  <div class='row clearfix'>
    <div class='col-md-12 column'>
      <form action='<%= identify_path %>' method='post' role='form'>
        <div class='panel panel-default'>
          <div class='panel-heading'>
            <h3 class='panel-title'>
              Identify
            </h3>
          </div>
          <div class='panel-body'>
            <div class='form-group'>
              <input type='text' class='form-control' name='input' placeholder='Enter an input' autofocus>
            </div>
          </div>
          <div class='panel-footer panel-footer-with-button clearfix'>
            <%= flash[:identify] %>
            <button type='submit' class='btn btn-primary pull-right'>Identify</button>
          </div>
        </div>
      </form>
    </div>
  </div>
  <div class='row clearfix'>
    <div class='col-md-6 column'>
      <div class='panel panel-default'>
        <div class='panel-heading'>
          <h3 class='panel-title'>
            Identity Mappings
          </h3>
        </div>
        <div class='panel-body'>
          <table class='table table-striped'>
            <thead>
            <tr>
              <th>Input</th>
              <th>Identity</th>
              <th>Delete</th>
            </tr>
            </thead>
            <tbody>
            <% @identities.each do |mapping| %>
                <tr>
                  <td><%= mapping.input %></td>
                  <td><%= mapping.identity %></td>
                  <td width='1'>
                    <form action='<%= delete_path %>' method='post'>
                      <input type='hidden' name='input' value='<%= mapping.input %>'>
                      <input type='hidden' name='identity' value='<%= mapping.identity %>'>
                      <button type='submit' class='btn btn-danger btn-xs pull-right'>X</button>
                    </form>
                  </td>
                </tr>
            <% end %>
            </tbody>
          </table>
        </div>
        <div class='panel-footer panel-footer-with-button'>
          <%= flash[:map] %>
          <%= flash[:delete] %>
          &nbsp;
        </div>
      </div>
    </div>
    <div class='col-md-6 column'>
      <div class='panel panel-default'>
        <div class='panel-heading'>
          <h3 class='panel-title'>
            Misses
          </h3>
        </div>
        <div class='panel-body'>
          <table class='table table-striped'>
            <thead>
            <tr>
              <th>Miss</th>
              <th>Add Identity</th>
              <th></th>
            </tr>
            </thead>
            <tbody>
            <% @misses.each do |miss| %>
                <form class='form-inline' action='<%= map_path %>' method='post'>
                  <tr>
                    <td><%= miss %></td>
                    <td>
                      <div class='form-group form-group-sm'>
                        <input type='hidden' name='input' value='<%= miss %>'>
                        <input type='text' class='form-control' name='identity' placeholder='Enter an identity'>
                      </div>
                    </td>
                    <td>
                      <button type='submit' class='btn btn-primary btn-xs pull-right'>Identify</button>
                    </td>
                  </tr>
                </form>
            <% end %>
            </tbody>
          </table>
        </div>
        <div class='panel-footer panel-footer-with-button clearfix'>
          <form action='<%= clear_path %>' method='post'>
            <%= flash[:clear] %>
            <button type='submit' class='btn btn-danger pull-right'>Clear</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/hid_ui/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HidUi</title>
  <%= stylesheet_link_tag    "hid_ui/application", :media => "all" %>
  <%= javascript_include_tag "hid_ui/application" %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>